backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: src/assets
public_folder: ../../assets/

collections:
  - name: "pages"
    label: "Pages"
    description: >
      Where you can edit pages.
    # folder: "src/markdowns/home"
    editor:
      preview: false
    files:
      - file: "src/markdowns/home/index.md"
        name: "index"
        label: "Home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "homepage",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - {
              label: "Video Banner",
              name: "videoBanner",
              widget: "object",
              required: false,
              fields:
                [
                  {
                    label: "Video File",
                    name: "videoFile",
                    widget: "file",
                    required: false,
                  },
                  {
                    label: "Video URL",
                    name: "videoUrl",
                    widget: "string",
                    required: false,
                  },
                  {
                    label: "Poster Image",
                    name: "posterImage",
                    widget: "image",
                    required: false,
                  },
                  {
                    label: "Alt Text",
                    name: "altText",
                    widget: "string",
                    required: false,
                  },
                ],
            }
